//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSpeedTest.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetTable1
    {
        public System.Guid id { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public System.DateTime col3 { get; set; }
        public Nullable<double> col4 { get; set; }
        public Nullable<double> col5 { get; set; }
        public Nullable<double> col6 { get; set; }
        public double col7 { get; set; }
        public Nullable<double> col8 { get; set; }
        public string col9 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public Nullable<long> col12 { get; set; }
        public Nullable<long> col13 { get; set; }
        public Nullable<bool> col14 { get; set; }
        public Nullable<bool> col15 { get; set; }
        public Nullable<bool> col16 { get; set; }
    }
}
